---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04
    named_run_list: apt
  - name: ubuntu-12.04
    named_run_list: apt
  - name: debian-8.2
    named_run_list: apt
  - name: debian-7.9
    named_run_list: apt
  - name: centos-7.2
    named_run_list: yum
  - name: centos-6.7
    named_run_list: yum
  - name: centos-5.11
    named_run_list: yum
  - name: freebsd-10.2
    named_run_list: freebsd
  - name: windows-2012r2
    named_run_list: windows

suites:
  - name: default
    named_run_list: default
    attributes:
      consul:
        config: &default-config
          bootstrap: true
          server: true
          datacenter: FortMeade
          encrypt: CGXC2NsXW4AvuB4h5ODYzQ==
  - name: git
    named_run_list: default
    attributes:
      consul:
        config: *default-config
        installation:
          provider: git
    excludes:
      - windows-2012r2
  - name: webui
    named_run_list: default
    attributes:
      consul:
        config:
          bootstrap: true
          server: true
          ui: true
          datacenter: FortMeade
          encrypt: CGXC2NsXW4AvuB4h5ODYzQ==
  - name: acl
    named_run_list: acl
    attributes:
      consul:
        config:
          bootstrap: true
          server: true
          datacenter: fortmeade
          acl_master_token: doublesecret
          acl_datacenter: fortmeade
          acl_default_policy: deny
    excludes:
      - windows-2012r2
      - centos-7.2
      - centos-6.7
      - centos-5.11
